### ISSUE TITLE
Typo breaks linux support

### ISSUE THREAD

**Issue by ILOVEPIE** [StarMade/SMEdit#4]
There is a typo in Boot.java that breaks linux support for SMEdit.
There is an extra n at the end of jo.sm.ui.RenderFrame in the line for launching smedit on linux.

**Comment by csnewman** [comment]
As far as I am aware this is no longer the main repo for SMEdit however I am unsure whether the project is still being worked on as http://smedit.co/ is no longer online?

**Comment by ILOVEPIE** [comment]
BobbyBigHoof is still working on it.

**Comment by csnewman** [comment]
Do you know where the code is now being hosted?

**Comment by jjaquinta** [comment]
It used to be here https://code.google.com/p/smedit2/
BobbyBigHoof used to work on it. I think he stopped in 2014. If he started again, he kept it quiet.

**Comment by csnewman** [comment]
I assume this means we could pick up the project and continue it?
(If anyone wants to, you are more than welcome to add me on skype chandler.newman)

**Comment by jjaquinta** [comment]
I have no problem if people want to continue it. Even after BobbyBigHoof's changes, 95% of the code was written by mehg. I'm not possessive about it. I just think it's polite to keep the original developer in the loop.

**Comment by ILOVEPIE** [comment]
I talked with Bobby yesterday he's still working on it he's doing a major rework of it says going to take some time before any new commits come up

**Comment by jjaquinta** [comment]
He said that a year ago too. If there is someone keen on doing something, they should probably just fork it and go with it, rather than wait. But, then, I'm not seeing a lot of buzz around Starmade anyway so I'm not sure there is much of an audience anyway.

**Comment by bobbybighoof** [comment]
I have at no time made any indication that I had dropped this project or that I would not be continuing to develop on it. Let me point out that in the entire time I have been the assumed lead developer on this project the only person to even come to me personally when all of my contact information has been made more than generally public is "ILOVEPIE" No one has made any attempt to offer any help other than to sit and wait for when it might be open for them to take over, and that is poor work ethics to say the least.

**Comment by csnewman** [comment]
That's my concern, StarMade seems dead from my experiences and I'm not sure if its worth putting any effort into modding it (I have modding working as you can see from the other repos but I'm not sure if its worth finishing it). I have plans to work on my own game anyway so I might just forget about StarMade.

**Comment by csnewman** [comment]
@bobbybighoof I did not want it to seem like I was wanting to take over but I was thinking about finishing modding and working on the tools for the game in my spare time and I was just unsure if anyone was even working on this anymore however I see that this probably isn't worth it.

**Comment by bobbybighoof** [comment]
this is the null pointer that the game needs to get past and it will get past it also why I'm in not rush to transform smedit with ever change made to the game.

**Comment by jjaquinta** [comment]
I got really frustrated a few years ago doing a bunch of stuff for someone else's game. They decided, meh, and I was stuck with a bunch of stuff I couldn't use anywhere else because it was their IP. My wife suggested that my time was better spent on my own IP. I'd recommend the same to anyone else.

FWIW my current game is "Starlanes" and is out for the Amazon Echo. It's the only multi-player game out for that device and is significantly more advanced than anything else out for the Echo. It's kind of interesting, programming for an audio-only device. There's been some usability problems that have impacted retention. But I'm just about to release 2.0 with a full tutorial system to try to address those.

Ultimately the aim is to create a universe with a bunch of tie-in games and loosely connected gameplay between them. The basic geography is all accessible via REST APIs so people can do web apps, desktop, mobile, or more Alexa apps. I'd make the backbone public so any people adding stuff won't get caught in the same IP dilemma we've seen with Starmade. If anyone is interested there is a forum here: http://starlanes.freeforums.net a wiki here: http://starlanes.wikia.com/ or you can drop me a line.
